import { defineTool } from "@github/copilot-sdk";

interface GenerateCodeArgs {
  vendor: string;
  changeDescription: string;
  currentAdapterPath: string;
}

interface GeneratedCode {
  vendor: string;
  filePath: string;
  language: string;
  code: string;
  changesSummary: string;
  testSuggestions: string[];
}

/**
 * Tool: generate_adapter_code
 * Generates updated adapter/integration code based on detected API changes.
 * Uses Copilot's agentic capabilities to produce enterprise-grade TypeScript.
 */
export const generateAdapterCode = defineTool("generate_adapter_code", {
  description:
    "Generate updated adapter/integration code for a vendor based on detected API changes. Produces TypeScript code with proper error handling, retry logic, and types.",
  parameters: {
    type: "object" as const,
    properties: {
      vendor: {
        type: "string",
        description: "The vendor name (e.g., 'stripe', 'shippo').",
      },
      changeDescription: {
        type: "string",
        description: "Description of the API change that needs to be addressed.",
      },
      currentAdapterPath: {
        type: "string",
        description: "Path to the current adapter file that needs updating.",
      },
    },
    required: ["vendor", "changeDescription", "currentAdapterPath"],
  },
  handler: async (args: GenerateCodeArgs): Promise<GeneratedCode> => {
    const { vendor, changeDescription, currentAdapterPath } = args;

    // In production, Copilot agent would analyze the current adapter code,
    // understand the API change, and generate the updated code.
    // Here we demonstrate the pattern with a Stripe example.
    const templates: Record<string, GeneratedCode> = {
      stripe: {
        vendor: "Stripe",
        filePath: currentAdapterPath,
        language: "typescript",
        code: `// Updated Stripe Payment Adapter — auto-generated by RetailAPIGuardian
// Change: ${changeDescription}
import Stripe from 'stripe';

interface PaymentRequest {
  amount: number;
  currency: string;
  paymentMethodId: string; // Updated: was 'source', now 'payment_method'
  customerId?: string;
  metadata?: Record<string, string>;
}

interface PaymentResult {
  success: boolean;
  intentId: string;
  status: string;
  error?: string;
}

const MAX_RETRIES = 3;
const RETRY_DELAY_MS = 1000;

export async function createPayment(
  stripe: Stripe,
  request: PaymentRequest
): Promise<PaymentResult> {
  let lastError: Error | undefined;

  for (let attempt = 1; attempt <= MAX_RETRIES; attempt++) {
    try {
      const intent = await stripe.paymentIntents.create({
        amount: request.amount,
        currency: request.currency,
        payment_method: request.paymentMethodId, // UPDATED: was 'source'
        customer: request.customerId,
        metadata: request.metadata,
        confirm: true,
        automatic_payment_methods: {
          enabled: true,
          allow_redirects: 'never',
        },
      });

      return {
        success: intent.status === 'succeeded',
        intentId: intent.id,
        status: intent.status,
      };
    } catch (err) {
      lastError = err as Error;
      if (attempt < MAX_RETRIES) {
        await new Promise(r => setTimeout(r, RETRY_DELAY_MS * attempt));
      }
    }
  }

  return {
    success: false,
    intentId: '',
    status: 'failed',
    error: lastError?.message ?? 'Unknown error after retries',
  };
}`,
        changesSummary:
          "Replaced deprecated 'source' parameter with 'payment_method'. Added automatic_payment_methods configuration. Added retry logic with exponential backoff.",
        testSuggestions: [
          "Test payment creation with valid payment_method ID",
          "Test retry behavior on transient Stripe errors",
          "Test error handling for invalid payment_method",
          "Verify backward compatibility with existing order flow",
        ],
      },
      shippo: {
        vendor: "Shippo",
        filePath: currentAdapterPath,
        language: "typescript",
        code: `// Updated Shippo Shipping Adapter — auto-generated by RetailAPIGuardian
// Change: ${changeDescription}

interface ShippingRateRequest {
  fromAddress: Address;
  toAddress: Address;
  parcel: Parcel;
  carrier?: string;
}

interface Address {
  street1: string;
  city: string;
  state: string;
  zip: string;
  country: string;
}

interface Parcel {
  length: number;
  width: number;
  height: number;
  weight: number;
  unit: 'in' | 'cm';
  weightUnit: 'lb' | 'kg';
}

interface ShippingRate {
  carrier: string;
  service: string;
  amount: number;
  currency: string;
  estimatedDays: number;
}

// UPDATED: Using v2/rates endpoint
const SHIPPO_API_BASE = 'https://api.goshippo.com/v2'; // was /v1

export async function getRates(
  apiKey: string,
  request: ShippingRateRequest
): Promise<ShippingRate[]> {
  const response = await fetch(\`\${SHIPPO_API_BASE}/rates\`, {
    method: 'POST',
    headers: {
      'Authorization': \`ShippoToken \${apiKey}\`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      address_from: request.fromAddress,
      address_to: request.toAddress,
      parcel: request.parcel,
      carrier_account: request.carrier,
    }),
  });

  if (!response.ok) {
    throw new Error(\`Shippo API error: \${response.status} \${response.statusText}\`);
  }

  const data = await response.json();
  // UPDATED: v2 response schema uses 'results' instead of 'rates'
  return (data.results ?? []).map((r: any) => ({
    carrier: r.provider,
    service: r.servicelevel?.name ?? r.service,
    amount: parseFloat(r.amount),
    currency: r.currency,
    estimatedDays: r.estimated_days ?? r.days,
  }));
}`,
        changesSummary:
          "Migrated from /v1/rates to /v2/rates endpoint. Updated response parsing for new schema (results vs rates, provider vs carrier).",
        testSuggestions: [
          "Test rate retrieval with v2 endpoint",
          "Verify response mapping from new schema",
          "Test error handling for invalid addresses",
          "Compare v1 vs v2 response equivalence",
        ],
      },
    };

    const key = vendor.toLowerCase();
    if (templates[key]) {
      return templates[key]!;
    }

    return {
      vendor,
      filePath: currentAdapterPath,
      language: "typescript",
      code: `// Adapter update for ${vendor} — requires manual review\n// Change: ${changeDescription}\n// TODO: Implement adapter updates based on API change analysis`,
      changesSummary: `Generic adapter update needed for ${vendor}: ${changeDescription}`,
      testSuggestions: [
        "Validate updated endpoint connectivity",
        "Test response schema compatibility",
        "Verify error handling",
      ],
    };
  },
});
